dependencies:
- name: agile-project-manager
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.59
- name: agile-project-manager-composite
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.127
- name: agile-project-manager-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.81
- name: application-root
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.22
- name: authservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.17
- name: comments-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.50
- name: comments-service-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- alias: dex
  name: dex
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 2.6.2
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.114
- name: gitprovider-sync-agent
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.45
- alias: apm-mongodb-ha
  name: mongodb-replicaset
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.14.0
- alias: userservice-mongodb-ha
  name: mongodb-replicaset
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.14.0
- alias: comments-service-mongodb-ha
  name: mongodb-replicaset
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.14.0
- alias: notifications-service-mongodb-ha
  name: mongodb-replicaset
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.14.0
- alias: gitprovider-sync-agent-mongodb-ha
  name: mongodb-replicaset
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.14.0
- name: notifications-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.11
- name: notifications-service-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: userservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.48
