dependencies:
- name: agile-project-manager
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.43
- name: agile-project-manager-composite
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.67
- name: agile-project-manager-frontend
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
- name: application-root
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.19
- name: authservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: comments-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.38
- alias: dex
  name: dex
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 2.6.2
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.114
- name: gitprovider-sync-agent
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.30
- alias: gitprovider-sync-agent-mongodb
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.5.0
- alias: notifications-service-mongodb
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.5.0
- alias: apm-mongodb
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.5.0
- alias: comments-service-mongodb
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.5.0
- alias: userservice-mongodb
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.5.0
- name: notifications-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- name: userservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.32
- alias: apm-mongodb-ha
  name: mongodb-replicaset
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 3.14.0
