dependencies:
- name: agile-project-manager
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.14
- name: application-root
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: comments-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.27
- alias: dex
  name: dex
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 2.6.1
- name: dex-client-poc
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.114
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.114
- name: gitprovider-sync-agent
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- alias: apm-mongodb
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.5.0
- alias: comments-service-mongodb
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.5.0
- alias: userservice-mongodb
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.5.0
- name: notifications-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: userservice
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.15
- alias: notifications-service-mongodb
  name: mongodb
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 7.5.0
