PipelineSecrets: {}
apm-mongodb-ha:
  auth:
    enabled: false
  replicas: 3
application-root:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    host: jx-staging.ci.cloudsmart.io
    paths:
    - backend:
        serviceName: agile-project-manager-frontend
        servicePort: 80
      path: /()(assets/apm.*)
    - backend:
        serviceName: notifications-service-frontend
        servicePort: 80
      path: /()(assets/notifications.*)
    - backend:
        serviceName: jx-dex
        servicePort: 32000
      path: /()(dex.*)
    - backend:
        serviceName: agile-project-manager
        servicePort: 80
      path: /(api)/(projects.*)
    - backend:
        serviceName: agile-project-manager
        servicePort: 80
      path: /(api)/(issues.*)
    - backend:
        serviceName: agile-project-manager
        servicePort: 80
      path: /(api)/(pulls.*)
    - backend:
        serviceName: agile-project-manager
        servicePort: 80
      path: /(api)/(sprints.*)
    - backend:
        serviceName: authservice
        servicePort: 80
      path: /(api)/(auth.*)
    - backend:
        serviceName: userservice
        servicePort: 80
      path: /(api)/(user.*)
    - backend:
        serviceName: comments-service
        servicePort: 80
      path: /(api)/(topics.*)
    - backend:
        serviceName: notifications-service
        servicePort: 80
      path: /(api)/(notifications.*)
    - backend:
        serviceName: application-root
        servicePort: 80
      path: /()(.*)
    tls:
      secretname: tls-ci-cloudsmart-io-p
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
comments-service-mongodb-ha:
  auth:
    enabled: false
  replicas: 3
authservice:
  secret:
    localhost_secret: "vault:cloudsmart-cluster1/authservice:localhost"
  env:
    DEV_CLIENT_ID: localhost
    DEV_CLIENT_CALLBACK_URL: http://localhost:8400/auth/callback
dex:
  config:
    connectors:
    - config:
        clientID: vault:cloudsmart-cluster1/github-oauth:clientID
        clientSecret: vault:cloudsmart-cluster1/github-oauth:clientSecret
        getUserInfo: true
        redirectURI: https://jx-staging.ci.cloudsmart.io/dex/callback
        scopes:
        - openid
        - email
        - profile
        - groups
        - federated:id
      id: github
      name: github
      type: github
    enablePasswordDB: false
    issuer: https://jx-staging.ci.cloudsmart.io/dex
    logger:
      level: debug
    oauth2:
      alwaysShowLoginScreen: false
      skipApprovalScreen: true
    staticClients:
    - id: authservice
      name: Auth Service
      redirectURIs:
      - https://jx-staging.ci.cloudsmart.io/auth/callback
      secret: vault:cloudsmart-cluster1/authservice:secret
    - id: localhost
      name: Localhost
      redirectURIs:
        - http://localhost:8400/auth/callback
      secret: vault:cloudsmart-cluster1/authservice:localhost
    storage:
      config:
        inCluster: true
      type: kubernetes
    web:
      address: 0.0.0.0
  grpc: false
  https: false
  image: quay.io/dexidp/dex
  imageTag: v2.21.0
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
    enabled: true
    path: /dex
    tls: []
  ports:
    web:
      containerPort: 5556
      nodePort: 32000
      servicePort: 32000
  replicas: 1
  service:
    annotations: {}
    type: ClusterIP
expose:
  config:
    domain: ci.cloudsmart.io
    exposer: Ingress
    http: "false"
    tlsSecretName: tls-ci-cloudsmart-io-p
    tlsacme: "true"
    urltemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
  production: true
gitprovider-sync-agent-mongodb-ha:
  auth:
    enabled: false
  replicas: 3
jenkins:
  Servers:
    Global: {}
notifications-service-mongodb-ha:
  auth:
    enabled: false
  replicas: 3
prow: {}
userservice-mongodb-ha:
  auth:
    enabled: false
  replicas: 3
